# Generated by Django 5.1.6 on 2025-03-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
        migrations.AlterField(
            model_name='servicios',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
