# Generated by Django 5.1.6 on 2025-03-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoWebApp', '0002_producto_created_producto_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='Categoriaprod',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
